### ISSUE TITLE
Certains utilisateurs ont pu noter le même anime plusieurs fois

### ISSUE THREAD

**Issue by jilljenn** [mangaki/mangaki#123]
Et ça ça ne va pas du tout :D
Il faut ajouter la contrainte dans le modèle, et ajouter une [transaction atomique](https://docs.djangoproject.com/fr/1.9/topics/db/transactions/#controlling-transactions-explicitly) pour réparer la base existante.

**Comment by RaitoBezarius** [comment]
Should I put the meme?
