### ISSUE TITLE
Remplacer KNN par SVD

### ISSUE THREAD

**Issue by jilljenn** [mangaki/mangaki#139]
À présent qu'elle a été testée (`./mangaki/manage.py compare`).

**Comment by RaitoBezarius** [comment]
@jilljenn Can you do an update on this issue?

- What work is left to close this issue?
- What is blocking you to close the issue?
- Can we help you?

**Comment by jilljenn** [comment]
Featured in https://github.com/mangaki/mangaki/pull/276.
