### ISSUE TITLE
Mettre une couleur différente aux anime et mangas

### ISSUE THREAD

**Issue by jilljenn** [mangaki/mangaki#141]
Sinon les gens sont _confused_.

**Comment by jilljenn** [comment]
@Sedeto Tu as des idées de couleurs de fond qui iraient bien pour anime VS manga VS album ?

**Comment by jilljenn** [comment]
J'ai vu que @Elarnon avait commencé à faire des jolis bandeaux avec [Semantic UI](http://semantic-ui.com/views/card.html) pour distinguer anime et manga :) Vivement que ce soit en prod !

**Comment by RaitoBezarius** [comment]
@jilljenn Mais en vérité, l'histoire d'une refonte du design est plus compliqué que cela.
Cela demande un travail de groupe dessus avec l'équipe sur une semaine au moins, à mon avis.

Comme Jean-Charles l'a précisé à plusieurs reprises (qui n'est pas sur GitHub), et d'autres aussi le pensent : le design de Mangaki doit reprendre un coup de jeune en total.

Ceci fait partie probablement d'un des items de l'issue "Refonte du design de Mangaki".

**Comment by jilljenn** [comment]
Que fait-on ? Un changement de couleur de faible opacité ? Un emoji pour distinguer ? Un bandeau ?

**Comment by jilljenn** [comment]
https://codepen.io/eode9/pen/twkKm OK ?

**Comment by Sedeto** [comment]
Si tu penses qu'on peut minimiser le design au max, ça me semble bien
(marge au dessus et en dessous)
Si je fais des tests sur ton lien ça influe sur tes recherches ? Je
voudrais éviter de tout péter.

2017-06-20 12:30 GMT+02:00 Jill-Jênn Vie <notifications@github.com>:

**Comment by RaitoBezarius** [comment]
@Sedeto Non, ça n'influera pas sur son CodePen, tu peux expérimenter à souhait!

**Comment by jilljenn** [comment]
Notez : ce n'est pas de moi, j'ai juste tapé **corner ribbon css** dans Google et c'est le premier résultat.

OK j'avais pas compris ce que tu voulais dire par marge au-dessus et en dessous mais en fait tu parles du `line-height` ! :)

BTW ça pourrait être cool de modifier le CSS des cartes Mangaki par CodePen ;) On n'aurait pas grand-chose à faire en plus.
