### ISSUE TITLE
Les posters doivent être en local

### ISSUE THREAD

**Issue by jilljenn** [mangaki/mangaki#146]
Ce que je propose, c'est de lier vers `/static/img/posters/{{ id }}.jpg` lorsqu'il existe, et sinon de télécharger le poster dans le champ `source`, et en cas d'exception 404 rattrapée, ça se reconnecte à l'API myAnimeList.

**Comment by jilljenn** [comment]
Voilà. J'ai fait des tests sympa via ce notebook.

P. S. – L'API myAnimeList ne permet pas de chercher par ID. Juste par titre. C'est terrible.

**Comment by jilljenn** [comment]
Hum d'ailleurs ne pensez-vous pas que les posters seraient mieux dans `media` que dans `static` ?

**Comment by Elarnon** [comment]
+1 pour les posters dans `media`

**Comment by jilljenn** [comment]
Done by https://github.com/mangaki/mangaki/pull/173.
