### ISSUE TITLE
Normaliser le fonctionnement de doctor

### ISSUE THREAD

**Issue by RaitoBezarius** [mangaki/mangaki#151]
Dû à #98, je pense qu'il est bien dans un premier temps de normaliser le fonctionnement de l'outil `doctor`, avant de pouvoir continuer.

Comme @Elarnon le dit, c'est pas super cohérent, et ça aide vraiment pas.

**Comment by Elarnon** [comment]
Je ne suis pas certain de la pertinence de cette issue. #134 doit déjà (entre autres) détruire `manage.py doctor` et le remplacer par une UI dans le panel d'admin.

**Comment by RaitoBezarius** [comment]
@Elarnon Oh, mince. Loupé, en effet.
