### ISSUE TITLE
Reconsidérer l'utilisation d'une table Category plutôt qu'un dictionnaire statique

### ISSUE THREAD

**Issue by Elarnon** [mangaki/mangaki#157]
Dans #110 nous avons finalement opté pour une table `Category` plutôt qu'un champ indexé avec la liste des catégories en dur dans le code, essentiellement à la recherche du graal de permettre de rajouter des catégories facilement dans le code. Cependant:

 - En pratique, on veut à peu près toujours savoir si un objet est un anime, un manga ou autre quand on manipule un `Work`, et donc on se retrouve à faire des requêtes sur `Category` à tort et à travers (si on a oublié un `select_related`) on des jointures sur `Category` de partout, ce qui est un peu mieux mais pas complétement génial. Le premier cas à un effet très mauvais sur les performances, le second est mieux mais possibleement toujours mauvais (à étudier, ou pas). Bref, c'est pas pratique.
 - En vérité, ajouter une nouvelle catégorie demande plus que de changer la table `Category`: il faut de toute façon configurer le `urls.py`, possiblement ajouter quelques bouts de code spécifique pour afficher la catégorie et possiblement rajouter des champs dans la BDD (e.g. identifiant vers un site externe). L'objectif principal de cette approche est donc légèrement caduc.

Par conséquent, j'ouvre la discussion (enfin, je la déplace sur GitHub) : devrions-nous supprimer la table `Category` et revenir à un champ indexé directement dans la table `Work` (les arguments découlent des remarques ci-dessus) ?

**Comment by Elarnon** [comment]
Pas d'avis contraire ? Je fais une PR avec ce changement demain.

**Comment by RaitoBezarius** [comment]
Moi je suis complètement pour, @jilljenn dernier mot?

**Comment by RaitoBezarius** [comment]
Donc la décision est d'implémenter un dictionnaire static. Je pense qu'on close dès que #168 est mergé.
