### ISSUE TITLE
La génération des événements fait trop de requêtes SQL

### ISSUE THREAD

**Issue by Elarnon** [mangaki/mangaki#163]
Comme remarqué par @RaitoBezarius dans #162.

**Comment by Elarnon** [comment]
0.3, seriously ?

**Comment by RaitoBezarius** [comment]
On a beaucoup de choses en 0.2, mais j'ai aucune idée de la priorité des choses, faudrait qu'on révalue tout ça, donc c'est juste indicatif et probablement voué à changer
