### ISSUE TITLE
Rechercher des animes / mangas

### ISSUE THREAD

**Issue by RaitoBezarius** [mangaki/mangaki#17]
@jilljenn aimerait implémenter la recherche, on a plusieurs options mais on pense que pour se simplifier la vie: [Algolia](https://www.algolia.com/).

**Comment by jilljenn** [comment]
Que reste-t-il à faire ?

**Comment by RaitoBezarius** [comment]
Il y a un endpoint minimal dans #129

**Comment by RaitoBezarius** [comment]
Donc, un peu de contexte depuis notre discussion offline dans le train avec @Elarnon : 

- [ ] Il faut séparer l'API de la pull request, et juste laisser la recherche.
- [ ] Il faut conserver les paramètres `GET` (sort, etc...)
- [ ] Il faut vérifier que la recherche se comporte bien sur un gros nombre d'animes (dépendant de @jilljenn, il l'appelle le seed big data, _pun intended or not_).
- [ ] Rajouter un peu de styling, sympathique. Et virer l'ancien formulaire et input.

Pas besoin de JavaScript.

**Comment by RaitoBezarius** [comment]
Fixé, via #169

**Comment by jilljenn** [comment]
Il faut être superuser pour créer l'extension `pg_trgm`. Ça mérite peut-être un message dans la doc.
