### ISSUE TITLE
Faire des jolies pages d'erreur (404, etc.)

### ISSUE THREAD

**Issue by Elarnon** [mangaki/mangaki#172]

**Comment by ak114** [comment]
Go la faire à la tvtropes (mention spéciale à @jilljenn): Ta page charge une citation en rapport avec l'erreur et un fond lié à l'anime/manga d'où ça vient

Je pense m'y mettre asap si vous êtes d'accord avec l'idée.

**Comment by Elarnon** [comment]
Ça me paraît très bien ! 

Proposition d'implementation : un modèle contenant les différentes infos (code d'erreur, citation, manga associé). Il faut par ailleurs qu'un message explicite explique clairement l'erreur en plus de la citation.

**Comment by ak114** [comment]
Reçu, je m'y mets asap.

**Comment by RaitoBezarius** [comment]
C'est vraiment absurde qu'on ne puisse pas assigner une issue à des gens externes de l'organisation.
@ak114 Oublie pas de nous tenir au courant si tu rencontres des difficultés!

**Comment by ak114** [comment]
Ok je m'y connais pas du tout sur Django mais c'est possible de repasser une view de base ([Reference sur la doc](https://docs.djangoproject.com/en/1.9/ref/views/#the-404-page-not-found-view)) ? ça evite de remplacer les `raise Http404`.

**Comment by RaitoBezarius** [comment]
@ak114 Tu devrais `raise` un `Http404` avec un message probablement et le render dans le template `404.html`, enfin, le template qui sera render aura aussi la variable `exception` (la Http404).
Donc si tu mets un message dans ton exception, tu peux la récupérer depuis ton template et l'afficher.

À priori, tu as besoin de quatres infos:

- le code d'erreur, 404, 500, etc... Ça, c'est fourni par Django. (`isinstance`, ou whatever)
- citation
- ID du manga ou un moyen de faire un link vers le manga je pense.
- la version explicite du message: 404 (pas trouvé), 500 (JJ a cassé la production), etc...

**Comment by ak114** [comment]
D'accord, c'est ce que je pensais. Merci beaucoup du coup.

**Comment by ak114** [comment]
Bon, je l'ai laissé sans utiliser le model mais est-ce que déjà tout est bon et est-ce que vous êtes d'accord avec le model ?

https://github.com/ak114/mangaki/tree/error_pages

**Comment by RaitoBezarius** [comment]
@ak114 Ouvre une PR, on pourra voir le diff plus facilement

**Comment by Elarnon** [comment]
Quelques remarques :
- Il faut une ForeignKey (ManyToOne) plutôt qu'une OneToOne : il peut y avoir plusieurs tropes dans la même œuvre.
- Pour remplacer les vues d'erreur, il faut utiliser https://docs.djangoproject.com/en/1.9/topics/http/views/#customizing-error-views pour avoir des vraies vues Django. Il faut donc mettre e.g. `handler404 = 'mangaki.views.error_404'` dans `mangaki/urls.py`
- Il faudra faire une page HTML statique 500 pour quand Django est complètement dans les choux. Ça peut juste être un rendering fixe de la page 500 normal.

**Comment by ak114** [comment]
@Elarnon J'imagine que si tu veux ManyToOne, c'est pour garder la trope dans le modèle du Work (de là où on fait la ForeignKey d'ErrorTrope). Du coup j'imagine que si jamais on garde la trope directement dans le Work, c'est pour pouvoir également l'afficher sur la page du Work en question (un random pick dans le range de nombres de citations) ? Je sais pas si c'est ce à quoi tu penses du coup.

Après, du coup en ManyToOne ça veut dire qu'on importe directement chaque citation sans les associer à une erreur particulière et qu'on les balance également en random. Dans ce cas il suffirait de garder les quotes dans Work sans besoin de faire de modèle ErrorTrope ?

**Comment by RaitoBezarius** [comment]
@ak114 En fait avoir un ManyToOne c'est juste que tu peux avoir plusieurs citations qui proviennent d'un même Work.

Je me demande, si ça vaut le coup ou pas de faire un modèle Quote qu'on pourra réutiliser plus tard, @Elarnon ; du coup, le Trope n'a besoin que d'une relation One to One à une Quote ou alors One to Many si tu veux plusieurs quotes et les sélectionner en random.

@ak114 Tu peux pas garder les quotes dans le Work, c'est un array de string. Si tu fais ça, ça va être un peu dégueu.

**Comment by RaitoBezarius** [comment]
Done in #260.
