### ISSUE TITLE
Ajout de la position des utilisateurs sur une représentation "spatiale" des préférences globales

### ISSUE THREAD

**Issue by ghost** [mangaki/mangaki#180]
Dans [les slides](http://research.mangaki.fr/public/parisml-meetup.pdf) de la présentation faite par JJ (trouvée sur http://research.mangaki.fr), il y a un exemple de représentation des préférences des utilisateurs sous forme de carte 2D. Il pourrait être intéressant de permettre aux utilisateurs de se situer sur ce genre de cartes.

Je ne sais pas quels ont été les paramètres utilisés dans cette carte, et les zones ont été a priori annotées à la main (SF, Populaire, Chelou…), mais à la fois le calcul de ces annotations et la représentation dans le profil d'un utilisateur pourraient former quelque chose de sympa.
![Représentation des préférences (extrait de la présentation)](https://cloud.githubusercontent.com/assets/5124130/15244710/c7685efa-1902-11e6-83ce-d7534e23a33f.png)

**Comment by jilljenn** [comment]
Merci pour cette idée ! Actuellement, l'image est générée via matplotlib sur un notebook Jupyter, que nous pouvons t'envoyer. Il semblerait qu'un canvas serait plus propre.

Je vois plusieurs questions :

- Est-ce qu'on recalcule les projections à chaque chargement de page de profil ? Ça semble une mauvaise idée.
- Quand recalculerait-on les vecteurs propres ? Parce que du coup il faudrait vérifier que les annotations correspondent.

Ce qu'on peut faire, c'est par exemple ajouter à l'objet `Profile` des attributs `x` et `y` (ou un seul attribut qui contiendrait plusieurs coordonnées séparées par des virgules, mais je doute qu'on fasse de la 3D plus tard), et seulement update les `x` et `y` d'un utilisateur lorsqu'il se connecte sur sa page de profil.

Les vecteurs propres, seraient, eux, hardcodés. <3 (Je sais combien ça va faire plaisir à la team de lire ceci.)

Ça te dit ? Tu essaies d'installer Mangaki et je t'envoie le notebook par mail ?

**Comment by jilljenn** [comment]
P. S. – J'adore le « représentation spatiale » couplé à ton avatar :)

**Comment by jilljenn** [comment]
Bon je veux vraiment qu'on fasse ça. Si je vous file des coordonnées pour chaque `Work` (on les a dans t-SNE), quelle bibliothèque JavaScript suggéreriez-vous pour en afficher les titres, avec les posters, et pouvoir zoomer ?

**Comment by RaitoBezarius** [comment]
I'd say: plotly. But, it could be a PITA if our usecase is too complicated.
We could also just use a `<canvas />` and do everything ourselves.

**Comment by jilljenn** [comment]
Si @Stolinger tu as une idée ça m'intéresserait de développer ça avec toi, peut-être après l'analyse des posters ! Ce sera une feature essentielle pour rendre le site visuel et attractif :)

**Comment by jilljenn** [comment]
Ou un truc à base de d3.js ;) http://www.music-map.com

**Comment by RaitoBezarius** [comment]
@jilljenn Plotly est à base de d3.js et stack.gl mais ouais, on peut utiliser d3.js, c'est juste un peu plus low level

**Comment by jilljenn** [comment]
Fixed in #752 6 years later: https://mangaki.fr/map/
