### ISSUE TITLE
Unnecessary dependency: Pandas

### ISSUE THREAD

**Issue by RaitoBezarius** [mangaki/mangaki#197]
We should not depend on pandas, it makes Mangaki harder to install and developers less happy because of the long compile time.

Actually, we are using pandas _only for reading CSV_, which is (as @jilljenn said): **stupid** :smile: !

- Relevant lines: https://github.com/mangaki/mangaki/blob/master/mangaki/mangaki/management/commands/compare.py#L41 and https://github.com/mangaki/mangaki/blob/master/mangaki/mangaki/management/commands/compare.py#L41

I will come up with a simple replacement for the CSV loading.

EDIT: Harder than expected.
Reading the CSV is fine, but transforming it into a proper NumPy Array with the good data types is not trivial.

For ratings: we have Integer, Integer, String.
For works: we have Integer, String.

Now, we could just use a `StringIO` and do `np.fromfile` or `np.genfromtxt` with the proper dtypes.
Unfortunately, it looks like these functions are bugged in Python 3.5 and will throw a `TypeError: Can't convert 'bytes' object to str implicitly'`.

**Comment by Elarnon** [comment]
Something we discussed with @jilljenn the other day was to have `pandas` as requirement in a `requirements-research.txt` or `requirements-algo.txt` file that would be separated from the rest.

The `manage.py compare` management command will only be used in this context anyways, and pandas is incredibly useful in other cases. Do note that people can install the `python3-pandas` (or equivalent for their distro) and create the virtualenv with `--system-site-package` to avoid the compilation time; we could add that to the system dependencies.

**Comment by RaitoBezarius** [comment]
@Elarnon I also think that `pandas` is really useful for manipulating data or doing research around algorithms.

But requiring `pandas` with Python 3.5 makes it _really_ harder to just try out the `compare` command for anyone.

---
The case when you already created your virtualenv without `--system-site-packages` or the case where you cannot install `python(3)-pandas` from your system-wide package manager would require to compile `pandas` using `cython`, which results in: `pip install cython`.

So let's make a tradeoff, we could just replace the `read_csv` but still depend on `pandas` in notebooks,
I'll submit a PR, let me know your thoughts on it.

**Comment by Elarnon** [comment]
FWIW, you can add the `--system-site-packages` to an existing virtualenv without losing anything by calling `virtualenv` / `python -m venv` / `mkvirtualenv` / etc. with that flag on the virtualenv (e.g. `mkvirtualenv --system-site-packages mangaki`) while outside the virtualenv.

I'm fine with this either way.

**Comment by RaitoBezarius** [comment]
Closed as we agreed that `pandas` was more required than we thought.
We need now to document how to install `pandas` easily.
