### ISSUE TITLE
Environnement de développement Vagrant

### ISSUE THREAD

**Issue by RaitoBezarius** [mangaki/mangaki#2]
Ça serait absolument génial pour inviter les nouveaux contributeurs à pouvoir bosser rapidement et facilement sur Mangaki de fournir un Vagrantfile qui met en place un environnement de développement Mangaki avec un virtualenv, PostgreSQL et tout super bien configuré.

Bonus, le résultat nous donne des environnements isolés, et pas de conflit avec des instances ou du boulot d'un autre truc.

C'est juste histoire de `vagrant up` et `vagrant ssh` :).

**Comment by jilljenn** [comment]
Je vote Docker, en fait. Comme Hummingbird :
https://github.com/hummingbird-me/hummingbird/wiki/Setting-up-a-development-environment#docker-recommended

**Comment by RaitoBezarius** [comment]
Pour ma [défense](http://www.boycottdocker.org/). Je suis définitivement contre Docker.

**Comment by jilljenn** [comment]
OK, wow, je ne savais pas. Pour moi le fait qu'il soit utilisé dans https://github.com/jupyter/tmpnb est un gros plus. L'as-tu toi-même utilisé ?

**Comment by RaitoBezarius** [comment]
Je fus autrefois un gros fanboy de Docker et utilisateur inébranlable, jusqu'à que je me réveille un jour et que je me rends compte que Docker est rempli de défauts, et que je n'étais victime de l'overengineering, de la hype et du reste.

Non mais plus sérieusement, Docker n'est pas trop approprié pour des environnements de développement, déjà que pour des environnements de production, c'est chaud. Enfin, sans dérouler ma tapisserie sur Docker, on n'en aurait pas l'utilité.

Pour tmpnb, on a besoin d'une sandbox isolée sans bouffer les ressources d'une VM, Docker (voire LXC pour être plus précis) est carrément approprié.
Un env de dev, ça se lance une fois, et on l'utilise jusqu'à qu'on merde avec et qu'on le détruit et du coup, qu'on relance encore une fois.

D'ailleurs, n'oublions pas que Docker est grosso modo un frontend de la technologie LXC.
