### ISSUE TITLE
Les espaces avant '!' devraient être &nbsp;

### ISSUE THREAD

**Issue by a3nm** [mangaki/mangaki#207]
On observe par exemple certaines occurrences du phénomène susmentionné sur la page http://mangaki.fr/about/, où l'on peut déplorer l'apparition disgracieuse de retours chariot avant les points d'exclamation, ceci en violation des conventions typographiques usuelles.

**Comment by jilljenn** [comment]
Bonjour, nous avons bien reçu votre demande mais malheureusement nous ne parlons pas l'américain. Pourriez-vous traduire votre message ? Merci cordialement.

**Comment by RaitoBezarius** [comment]
Je pense qu'il faut rediriger toutes les ressources afin de tuer ce bogue qui me paraît relativement critique.

Après tout, les conventions de typographie sont au cœur de Mangaki, il est pour moi, hors de question, de continuer à voir de telles bavures sur un site aussi dirigé par la typographie.

Ouvrons une poule équestre.
