### ISSUE TITLE
Il n'y a pas de template pour le fichier settings.ini

### ISSUE THREAD

**Issue by jilljenn** [mangaki/mangaki#208]
Du coup, on doit découvrir par l'échec qu'il faut une entrée `DISCOURSE_API_USERNAME`.

**Comment by RaitoBezarius** [comment]
Je vois deux solutions qui ne s'excluent pas : 

- Écrire de la documentation sur `settings.ini`
- Écrire un template de `settings.ini` avec les options les plus fréquentes et référer le reste au `settings.py`

Solution plus élégante pour le futur : permettre un CLI qui génère la config (`mangaki quickstart`) copié sur le fonctionnement du `manage.py createsuperuser`.

**Comment by jilljenn** [comment]
[mal]
MAL_USER = XXX
MAL_USER_AGENT = XXX

[secrets]
SECRET_KEY = XXX
DB_PASSWORD = XXX
MAL_PASS = XXX

[hosts]
ALLOWED_HOSTS = *

Je ne sais pas à quoi sert DB_PASSWORD.

**Comment by RaitoBezarius** [comment]
@jilljenn Il arrive que les bases de données aient des mot de passe.
c.f. https://github.com/mangaki/mangaki/blob/master/mangaki/mangaki/settings.py#L95
