### ISSUE TITLE
Actual seed data is not working

### ISSUE THREAD

**Issue by jilljenn** [mangaki/mangaki#209]
Problème soulevé par @fravoi et @Zeletochoy.

**Comment by RaitoBezarius** [comment]
Afin de résoudre le problème définitivement, il serait préférable de faire ceci :

- [ ] documenter comment fabriquer la small seed data et la big seed data.
- [ ] produire les deux.
- [ ] uploader les deux.
- [ ] automatiser la regénération des deux. (plus tard)

**Comment by jilljenn** [comment]
Il y a déjà un notebook, probablement obsolète :
https://github.com/mangaki/mangaki/blob/master/notebooks/Make%20seed%20data.ipynb

**Comment by RaitoBezarius** [comment]
Je pense que d'ailleurs, on voudrait plutôt une management command qu'une notebook :angel:

**Comment by RaitoBezarius** [comment]
Des chantiers ont commencé à partir de fcfaccbd9c341b35b81338237bad5a7e1a5069c2.

**Comment by RaitoBezarius** [comment]
Alors en fait:

— Il faut dumper juste le strict nécessaire, a.k.a des models de works, artists, etc…
— Pour les users, on s'en fiche. Cela sera l'objet d'une autre issue ou discussion.

**Comment by jilljenn** [comment]
Now it works.
