### ISSUE TITLE
Fresh install of Mangaki

### ISSUE THREAD

**Issue by jilljenn** [mangaki/mangaki#212]
- [x] Le Vagrant est cassé (voir avec Elarnon pour plus de détails)
- [ ] Les requirements (.txt & Vagrant) ne prennent pas en compte les versions des fichiers
- [x] La version de dev ne devrait pas requérir des paramètres Discourse
- [ ] Remplacer le settings.ini par un settings.yaml

En termes d'infra :
- beta.mangaki.fr est mort
- Le DigitalOcean est cassé
- Elarnon veut bien setup un serveur de mail s'il n'a pas de playbook Ansible à faire

**Comment by RaitoBezarius** [comment]
c.f. #243 pour le Vagrant.

**Comment by jilljenn** [comment]
settings.ini remplacé par YAML ne me semble pas prioritaire.
En revanche, le requirements-dev.txt ne spécifie pas de version de Django et c'est embêtant. On ajoute 1.10 et on ferme cette issue ?
