### ISSUE TITLE
Let's rewrite the AniDB utility

### ISSUE THREAD

**Issue by RaitoBezarius** [mangaki/mangaki#220]

**Comment by RaitoBezarius** [comment]
Some work started eff1fca here.

**Comment by Elarnon** [comment]
Can you define "broken"?

**Comment by RaitoBezarius** [comment]
@Elarnon Right, as far as I recall, the AniDB library in the Mangaki codebase is unable to fetch and search properly all the data from AniDB (ie: a lot of fields didn't have the parsing logic from XML to strings / numbers).

Otherwise, take a look to the diff in eff1fca — it speaks from itself.

**Comment by Elarnon** [comment]
eff1fca is actually unreadable because of all the whitespace changes within. Can we please fix the whitespace first, then make changes (or the other way around)?

I guess what I'm asking is whether this is broken as in "it currently doesn't work at all", or broken as in "it works but may sometimes have weird issues".

**Comment by RaitoBezarius** [comment]
Actually, I have completely forgotten about this, the former version of the AniDB library had broken indentation also…

Sorry for this. I'll attempt to make a commit between them to fix the whitespace first and then, have the changes, only if there is a simple way. I admit that it might be not _that_ useful to spend time on fixing whitespace *then* applying changes, just for the sake of readability, IMHO.

> I guess what I'm asking is whether this is broken as in "it currently doesn't work at all", or broken as in "it works but may sometimes have weird issues".

If "working" for you is syntactically correct, then yes, it works.
But, if "working" is usable for Mangaki operations, then not really.

**Comment by RaitoBezarius** [comment]
Rather than saying it's broken, we should say that we would like to rewrite the AniDB utility (maybe, from scratch or using some external dep).
