### ISSUE TITLE
Plug an email server

### ISSUE THREAD

**Issue by RaitoBezarius** [mangaki/mangaki#222]
For the next deployment of #171

**Comment by RaitoBezarius** [comment]
Objective:

- Mailing lists (mailman?)
- Emails for members (Modoboa?)

**Comment by jilljenn** [comment]
Thanks https://github.com/prologin/django-massmailer and #657!

**Comment by RaitoBezarius** [comment]
This does not solve the problem of adding a real email server, I suppose? We still need something akin to Modoboa.

**Comment by RaitoBezarius** [comment]
This is now solved, it is handled by my Kurisu mail server, with redundant encrypted backups in my DC1.

We may want mailing list at some point, uncertain how, so let's track this in another issue.
I guess we want https://listmonk.app/ at some point.
