### ISSUE TITLE
Move Jupyter Notebooks to another repository

### ISSUE THREAD

**Issue by RaitoBezarius** [mangaki/mangaki#224]
Having notebooks is fine and cool.
But having too much notebooks might be bad.

What about moving them into another repository of the Mangaki org ?

`mangaki/notebooks` for example?

**Comment by RaitoBezarius** [comment]
/ping @jilljenn — what is your take on this?

**Comment by jilljenn** [comment]
Je ne vois pas le rapport entre « Il y a trop de notebooks » et « On va les mettre dans un autre dossier ».

**Comment by RaitoBezarius** [comment]
@jilljenn Tout le monde ne veut pas nécessairement cloner des notebooks avec le repo de Mangaki. Les mettre dans un autre repo, c'est aussi simplifier le suivi de l'historique des notebooks.

**Comment by RaitoBezarius** [comment]
Not relevant anymore, I guess, @jilljenn ? So I close.
