### ISSUE TITLE
Recovery password

### ISSUE THREAD

**Issue by pineki** [mangaki/mangaki#238]
Bonjour,
J'ai essayé de récupérer mon mot de passe mais je n'ai jamais reçu le mail de réinitialisation.

**Comment by RaitoBezarius** [comment]
@pineki As-tu tenté de regarder dans tes spams?

(/ping @jilljenn — le serveur mail est-il vivant?)

**Comment by pineki** [comment]
@RaitoBezarius Oui

**Comment by RaitoBezarius** [comment]
@pineki On est en train de regarder le problème, pourrais-tu nous dire quel est ton fournisseur d'adresse email ? (GMail, Hotmail, …, ou self-hosted?)

**Comment by pineki** [comment]
@RaitoBezarius Le voici: kristin.zg@gmail.com
Mon compte à été crée à la Japan expo (2016) sur l’ordinateur du président du site.

**Comment by jilljenn** [comment]
Bonjour, c'est corrigé :) Des paramètres à changer. Merci !
