### ISSUE TITLE
Investiguer le déploiement de Mangaki en tant que paquet PyPI

### ISSUE THREAD

**Issue by Elarnon** [mangaki/mangaki#242]
Parceque en fait ça fait complétement plus de sens que de cloner des dépots git à tout va.

**Comment by RaitoBezarius** [comment]
@Elarnon It's going to be fixed in #321, right?

**Comment by Elarnon** [comment]
Yes.

**Comment by RaitoBezarius** [comment]
Closing as #321 is now merged.
