### ISSUE TITLE
Python 3.6, when?

### ISSUE THREAD

**Issue by RaitoBezarius** [mangaki/mangaki#247]
Python 3.6 is out. :fireworks: 

Does it make sense to move to Python 3.6?

(it's not an issue that requires immediate action, rather, long-term thoughts about what should we do in the future.)

**Comment by jilljenn** [comment]
Now.

**Comment by jilljenn** [comment]
For your information, I managed to run the Mangaki website on Python 3.6.1. (I just had to convert a map to a list, or some of the like.)

**Comment by jilljenn** [comment]
It works now :)
