### ISSUE TITLE
Posters retrieved should have unique filenames

### ISSUE THREAD

**Issue by jilljenn** [mangaki/mangaki#251]
I used to use `{{ work_id }}.jpg` but maybe this is not good: people can download every poster using a script. Do you find other reasons?

Possibly, a padded hash is better.

Useful discussion: https://github.com/mangaki/mangaki/pull/248#discussion_r99206237

**Comment by RaitoBezarius** [comment]
@jilljenn We cannot prevent people to download every poster using a script.
Even by hashing all our posters.

Simple reason is that: they can always crawl our pages using a scraper.

To me, the arguments in favour of unique filenames that I currently see are:

- Easy cache busting when having new posters for a work.
- No weird collisions can happen during simultaneous poster updates (e.g. two admins downloading two different posters).

**Comment by RaitoBezarius** [comment]
According to @Elarnon, it should not happen, closing.
