### ISSUE TITLE
Move the current README to README.fr and add an english README

### ISSUE THREAD

**Issue by RaitoBezarius** [mangaki/mangaki#256]
I feel mixed about this.

What do you think, @jilljenn, @Elarnon, @vendethiel ?

P.S. : 2⁸-th issue.

**Comment by vendethiel** [comment]
I wouldn't prioritize it over i18n-ing the website itself, I guess?

**Comment by RaitoBezarius** [comment]
@vendethiel In fact, there was a lot of concerns against i18n raised during our meeting at Paris (c.f. notes sent by email).

The main concerns were:

- Translating the system messages and the website content would be easy.
- But, translating the database content is beyond our ability in terms of manpower and resources.
- Examples of what does not wish for includes [annict](https://annict.com/) which shows English and Japanese at the same time.

**Comment by RaitoBezarius** [comment]
@jilljenn Don't forget to close it.
