### ISSUE TITLE
Un appel au KNN rend les backups SVD/ALS/WALS caduques

### ISSUE THREAD

**Issue by jilljenn** [mangaki/mangaki#267]
Forcément, les fichiers Pickle SVD/ALS/WALS dépendent du ratings.pickle en cours, qui est écrasé par un quelconque appel au KNN (c'est-à-dire, par défaut). Il faudrait éviter ça, par exemple en insérant les ratings dans les backups SVD et al.

**Comment by RaitoBezarius** [comment]
Agh. Should the SVD / ALS / WALS also insert the ratings into the good pickle files?
I think it may be the time to give a longer thought about how should we handle the ratings cache file.
