### ISSUE TITLE
Typeahead consomme trop d'espace dans localStorage

### ISSUE THREAD

**Issue by RaitoBezarius** [mangaki/mangaki#28]
Typeahead est inclus partout même lorsqu'il est pas utilisé ou lorsqu'on est pas authentifié, je ne sais pas exactement ce qui se passe.

Mais visiblement, il consomme trop:
![QuotaExceededError](https://sc-cdn.scaleengine.net/i/36c4e52a66759480319980168a2f8660.png)

**Comment by jilljenn** [comment]
My guess: typeahead est activé sur toutes les pages mais le prefetch n'est que sur les vues AnimeList ou AnimeDetail, mais comme il met les anime/manga dans le LocalStorage c'est fichu sur toutes les pages.

**Comment by RaitoBezarius** [comment]
Fermé dans #119
