### ISSUE TITLE
[Backoffice] Impossibilité de modifier une oeuvre pour corriger des associations aux artistes

### ISSUE THREAD

**Issue by SubaruSumeragi** [mangaki/mangaki#296]
Impossibilité de modifier manuellement une oeuvre pour corriger des associations aux artistes

**Comment by jilljenn** [comment]
Attends j'ai réussi, comment ça se fait que tu n'y arrives pas ? Je vais check si tu as bien toutes les permissions.

**Comment by jilljenn** [comment]
Désolé, tu n'avais effectivement pas la permission `Staff` !
