### ISSUE TITLE
Doctor management command is utterly broken

### ISSUE THREAD

**Issue by RaitoBezarius** [mangaki/mangaki#300]
The algorithm does not make a lot of sense.

- It deletes animes IDs, but it can fail due to the fact that IDs are in a big heap.
- There is a lot of false positives w/o any relevant reason (like, why Dimension W and Senki Zesshou Symphogear G is the same thing with *different* external posters?)
- Rename tasks should not be added if the title is exactly *the same*.
- All works do not have sources, that should not be considered as a different source, but rather, take the most common sources of all duplicates and set it for all.
- For UX/UI purpose, default IMHO should be yes so that we can easily spam [Enter]. Warning should be added (with color preferably) when too many variables are different.
- It works only for animes, but the logic should be exactly the same for manga and animes, as they also have a MAL ID (yes, it is called `series_mangadb_id`).
- Exceptions should not hinder the process.
- Everything should be wrapped into a transaction to undo changes easily by Ctrl-C or another keystroke (undo last change, whatever).

**Comment by RaitoBezarius** [comment]
Theorically, we should use the logic of #299 to re-implement properly `doctor.py`.

**Comment by RaitoBezarius** [comment]
Let's kill it with :fire:.

**Comment by jilljenn** [comment]
Did you kill it?
