### ISSUE TITLE
Suppression de rating

### ISSUE THREAD

**Issue by SubaruSumeragi** [mangaki/mangaki#319]
Il semble impossible pour un utilisateur de supprimer un rating fait par erreur.

**Comment by vendethiel** [comment]
C'est un peu lié à #7 et #18.

**Comment by jilljenn** [comment]
C'est étrange, ça a été fix dans https://github.com/mangaki/mangaki/pull/306 le 4 mai, peut-être que la prod n'a pas été mise à jour à ce moment-là ?
