### ISSUE TITLE
Créer une classe Partner

### ISSUE THREAD

**Issue by jilljenn** [mangaki/mangaki#32]
Il y a trop de partenaires sur la page d'accueil pour que ce soit hardcodé. En plus, je crois que les définitions des logos sont bien trop grosses, ce qui rend la page lourde à charger. Je les verrais bien tous sur une ligne ou deux, dans l'idéal avec des logos en noir et blanc qui lorsqu'on hover passent en couleurs.

**Comment by Mako-kun** [comment]
Pour l'instant, je ne sais pas comment faire le lien entre une classe Partner, des objets représentant les différents logos et la page d'accueil mais je sais faire une chose : c'est l'affichage de tout ça en CSS.
Donc pour l'instant, j'ai adapté l'existant en rétrécissant les logos pour qu'ils soient beaucoup plus légers et en modifiant le CSS (et aussi un peu la view) pour obtenir le résultat ci-dessous.

![sans titre](https://cloud.githubusercontent.com/assets/16636163/12223166/7cd1d9ae-b7d0-11e5-9915-37c45b12ec60.jpg)

Mais à terme, je pense que c'est intéressant comme idée le coup de la classe Partner, ça serait plus simple pour gérer les différents partenaires. Car comme tu dis, actuellement, c'est hardcodé et y en a beaucoup trop. :)
C'est juste qu'avec mes capacités actuelles je peux pas faire.

**Comment by RaitoBezarius** [comment]
C'est absolument génial Benoît, si je peux me permettre, pourrais-tu forker
Mangaki et mettre le code dans une nouvelle branche (potentiellement
feature/partner_css), et ouvrir une pull request vers Mangaki?

  

Quant à la classe Partner, @jilljenn tu parlais d'un modèle ou bien... ?

(je pense à un composant Rea-//PAN//)

  

<br  

Kind regards,

—

Ryan Lahfa

> On Jan 10 2016, at 7:30 pm, Benoît Fort &lt;notifications@github.com&gt;
wrote:  

>

> Pour l'instant, je ne sais pas comment faire le lien entre une classe
Partner, des objets représentant les différents logos et la page d'accueil
mais je sais faire une chose : c'est l'affichage de tout ça en CSS.  
Donc pour l'instant, j'ai adapté l'existant en rétrécissant les logos pour
qu'ils soient beaucoup plus légers et en modifiant le CSS (et aussi un peu la
view) pour obtenir le résultat ci-dessous.

>

> [![sans titre](https://cloud.githubusercontent.com/assets/16636163/12223166
/7cd1d9ae-b7d0-11e5-9915-37c45b12ec60.jpg)](https://cloud.githubusercontent.co
m/assets/16636163/12223166/7cd1d9ae-b7d0-11e5-9915-37c45b12ec60.jpg)

>

> Mais à terme, je pense que c'est intéressant comme idée le coup de la classe
Partner, ça serait plus simple pour gérer les différents partenaires. Car
comme tu dis, actuellement, c'est hardcodé et y en a beaucoup trop. :)  
C'est juste qu'avec mes capacités actuelles je peux pas faire.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/mangaki
/mangaki/issues/32#issuecomment-170379151).![](https://github.com/notification
s/beacon/AATMxJa4TcwU6Alyi7R-ef3ERf8PlnbLks5pYprbgaJpZM4G_Vx_.gif)

**Comment by Mako-kun** [comment]
Merci beaucoup ! :)
Je me débats un peu avec Github (je débute) mais je pense avoir compris le fonctionnement global de la chose.
Jill-Jênn m'a proposé de me dépatouiller avec la classe Partner à créer : j'ouvre quand même un pull request vers Mangaki de ce que j'ai fait ou vaut mieux d'abord que je fasse le plus de choses possible avant ? ^^

**Comment by RaitoBezarius** [comment]
Rien ne t'empêche d'ouvrir la pull request dès maintenant et d'ajouter progressivement la classe Partner autant que tu puisses le faire!
Tu n'auras qu'à préciser dans la PR quand tu seras prêt pour qu'on puisse la fusionner avec Mangaki.

**Comment by Mako-kun** [comment]
Entendu, je ne savais pas qu'on pouvait faire une chose pareille. J'ouvre une pull request tout de suite alors. :)
Merci !
