### ISSUE TITLE
Module d'aide utilisateur

### ISSUE THREAD

**Issue by jilljenn** [mangaki/mangaki#33]
Il faut faire une page accessible par mangaki.fr/help qui détermine la contribution (fusion d'œuvres, poster manquant, etc.) la plus prioritaire.

**Comment by RaitoBezarius** [comment]
Pour plus d'informations, [cet email est très enrichissant](https://groups.google.com/forum/#!msg/mangaki/9_ig24inq2I/CSQbg-B-JwAJ).

**Comment by jilljenn** [comment]
Je considère mangaki.fr/fix comme étant cela. C'était dans quelle milestone déjà ?
