### ISSUE TITLE
Les liens de tri ne fonctionnent pas sur le profil

### ISSUE THREAD

**Issue by SubaruSumeragi** [mangaki/mangaki#336]
Les liens de tri pour changer d'algo sur les profils ne fonctionnent et conservent l'ordre alphabétique.

![2017-05-29_165407](https://cloud.githubusercontent.com/assets/4798290/26554279/9788afa0-448f-11e7-959f-9d387ca594d7.png)

Tri ALS
![als](https://cloud.githubusercontent.com/assets/4798290/26554320/cb32ca8e-448f-11e7-9bba-99fed7628737.png)

Tri SVD
![svd](https://cloud.githubusercontent.com/assets/4798290/26554336/d959975a-448f-11e7-99ce-d8326bd65295.png)

**Comment by RaitoBezarius** [comment]
@jilljenn Have we reload the SVD / ALS pickles?

**Comment by jilljenn** [comment]
No, I want to do this today.

**Comment by RaitoBezarius** [comment]
AFAIK, it has been done.
