### ISSUE TITLE
When re-deploying, put current instance of Mangaki in maintenance

### ISSUE THREAD

**Issue by RaitoBezarius** [mangaki/mangaki#337]
AFAIK, the current Ansible playbook does not try to put the current instance of Mangaki in maintenance.

We should do this, perform upgrade operations, and end the deployment sequence.

It should be relatively easy to insert sort of `mangaki_sync_maintenance` flag inside of the playbook, am I right @Elarnon ?

Should fix a item of #228.

**Comment by jilljenn** [comment]
Yes the current nginx file on Mangaki.fr handles 503 maintenance status, are you interested in having a look? I just need to put a file in a certain directory to enable it.

**Comment by RaitoBezarius** [comment]
I can imagine the contents, but I wonder if it'd be better to implement it at the Django level, with a management command such as `manage.py maintenance` ?

**Comment by RaitoBezarius** [comment]
Closed in favour of #764
