### ISSUE TITLE
Action admin pour fusionner des œuvres

### ISSUE THREAD

**Issue by jilljenn** [mangaki/mangaki#34]
Si jamais on le fait, il faudra avoir une page intermédiaire « Êtes-vous sûr de vouloir fusionner [telle œuvre] (X votes) avec [telle œuvre] (Y votes) ? », « Quel poster conserver ? » etc.

Pour cela, [la doc officielle](https://docs.djangoproject.com/en/1.9/ref/contrib/admin/actions/), [un post de blog de 2010](http://www.jpichon.net/blog/2010/08/django-admin-actions-and-intermediate-pages/) et surtout [un snippet de 2015](https://gist.github.com/rturowicz/5472482).

**Comment by Elarnon** [comment]
Hmm, tu veux dire quelque chose comme e0a86bb5724cdd54a9cd16f35fe7175c59786d74 ?

**Comment by jilljenn** [comment]
C'est très fort possible.

**Comment by Elarnon** [comment]
Fusion AnimeAdmin.merge -> WorkAdmin.merge

**Comment by jilljenn** [comment]
Cette issue n'est pas terminée car :

- lorsqu'on fusionne deux (ou plus !) œuvres, Mangaki doit demander à l'admin de cocher des boutons radio pour savoir quoi garder (quel poster, quel synopsis), et en priorité, pas du vide ;
- ça va être sympa pour les tags aussi ; j'imagine que par défaut on met l'union des tags ;
- si une même personne a mis des Ratings différents pour chaque objet, on met celui de date la plus récente, ou s'il n'y a pas de date, celui de plus grand ID.

Comme on peut être amené à fusionner plusieurs œuvres, est-ce qu'on affiche ça sous forme de tableau ? :) (Ça fait longtemps que je n'ai pas fait de tableau, tiens.)

Et après ça, on pourra mettre des clusters à review.

**Comment by jilljenn** [comment]
Finally!
