### ISSUE TITLE
Set up beta / stable workflow with CircleCI / Ansible

### ISSUE THREAD

**Issue by RaitoBezarius** [mangaki/mangaki#345]
Now that Ansible has been merged and that we have tests, we should create a `stable` branch and "beta" branch (i.e. `master`) which will trigger an Ansible deployment when tests pass on the branch.

Also, once @jilljenn's server is moved on Mangaki's machines, we may also want to trigger auto-deployment on the `stable` branch to the production machine (if and only if tests pass, of course).

**Comment by RaitoBezarius** [comment]
Beta done.

**Comment by jilljenn** [comment]
Why is this issue still open? Don't you want to make different issues to get this micropleasure of GTD?

**Comment by RaitoBezarius** [comment]
No, because I like to do things like I initially planned to do :p.

**Comment by jilljenn** [comment]
Je ferme :) Rouvrez si besoin.
