### ISSUE TITLE
MAL CDN

### ISSUE THREAD

**Issue by SubaruSumeragi** [mangaki/mangaki#346]
Comme @RaitoBezarius l'a fait remarqué hier sur Slack on a plein d'images mortes sur le site, la raison en est simple : MAL a modifié, semble-t-il, l'URL de son CDN (cdn.myanimeliste.net est devenu myanimelist.cdn-dena.com).

Les DNS ne reconnaissent actuellement plus l'ancienne et il n'est pas certain que MAL corrige cela.

Ne pourrait-on pas faire une requête SQL pour corriger toutes les URL en cdn.myanimeliste.net afin de mettre le bon domaine à la place ? (l'arborescence du CDN n'a pas été modifiée)

**Comment by RaitoBezarius** [comment]
I think that this would be the job for a data migration.

**Comment by jilljenn** [comment]
Let's start with a minimal PR that fixes all links. Then think about poster downloads.
