### ISSUE TITLE
Redirected (phantom) works should not appear anywhere on the public website

### ISSUE THREAD

**Issue by RaitoBezarius** [mangaki/mangaki#359]
Introduced with #307, now `all_objects` (which is the default / base manager) returns all works when `objects` only returns non-phantom works (i.e. `redirect != None`).

This has caused a problem in the mosaic, ~~fixed in https://github.com/mangaki/mangaki/pull/358~~ to be fixed.

But the same problem remains and extra caution is necessary regarding linked objects fetching with `Work` instances.

**Comment by jilljenn** [comment]
Il faudrait écrire un test :

    There should not be Work with `redirect=True` in mosaïque

**Comment by jilljenn** [comment]
But, like @RaitoBezarius said orally, they should be considered for 301 redirects.
