### ISSUE TITLE
Importer sa MyAnimeList une seconde fois ne semble pas fonctionner

### ISSUE THREAD

**Issue by mrsalixor** [mangaki/mangaki#360]
Lorsque l'on essaye d'importer à nouveau sa MyAnimeList, la liste des notations Mangaki n'est pas mise à jour.

Typiquement, à la création de mon compte (~2 semaines), j'ai importé ma MAL sans aucun problème.
Aujourd'hui, j'ai essayé de l'importer de nouveau, et rien n'a changé.
J'ai ensuite essayé de supprimer toutes mes notations et d'importer à nouveau, toujours sans aucune conséquence, la liste des notations restant vide.

**Comment by RaitoBezarius** [comment]
Thanks @mrsalixor ; je regarde dès que j'ai du temps.
