### ISSUE TITLE
ratings.svg is imported for each work on your profile

### ISSUE THREAD

**Issue by RaitoBezarius** [mangaki/mangaki#363]
That's too much.

Solutions:

- pass the result  `{% static "img/ratings.svg" %}` from the top templates (annoying).
- hardcode (stupid).
- send help (appreciated).

**Comment by Elarnon** [comment]
Additional possible solutions : 

- Wrap that piece of code in `{% cache %}
- `{% get_static_prefix as STATIC_PREFIX %}` somewhere along the top of the template and use `{{ STATIC_PREFIX }}img/ratings.svg` here and on other places where the `{% static %}` overhead is too high.

Things that we can do anyways:
- Get rid of `mangaki/rating.html` and use a parameterized `mangaki/ratings.html` which has a built-in for loop. That'll *both* limit the number of `{% static %}` and divide the overall number of `{% include %}` by 6, which'll be great.
 - Let's not forget that on production settings (i.e. where perf matters), template are pre-compiled by Django, and the overhead may not be that important in that case.

**Comment by RaitoBezarius** [comment]
Closed in #364.
