### ISSUE TITLE
Sparse matrices should be used on certain algorithms

### ISSUE THREAD

**Issue by RaitoBezarius** [mangaki/mangaki#365]
Currently, only KNN/NMF uses an LIL sparse matrix format to build during `make_matrix` phase.

We should use either CSC / CSR / BSR for KNN, ALS, SVD and PCA.

WALS already uses a `SparseTensor` but I have yet to fully understand performance considerations.

**Comment by jilljenn** [comment]
It is now done, except for ALS.

**Comment by jilljenn** [comment]
I tried for ALS and it slowed it down. No need to do it then.
