### ISSUE TITLE
Il faut un bouton « Essayer » sur la page d'accueil pour les non inscrits

### ISSUE THREAD

**Issue by jilljenn** [mangaki/mangaki#413]
Sinon c'est dommage d'avoir fait tout ce boulot d'essai avant inscription ;p

**Comment by RaitoBezarius** [comment]
@jilljenn Do we agree on the fact that the "Try" button would only be a redirect on "Animes" mosaic?

**Comment by jilljenn** [comment]
Yes that's all.
