### ISSUE TITLE
« Anime que je veux voir » contient aussi les wontsee 🤣

### ISSUE THREAD

**Issue by jilljenn** [mangaki/mangaki#441]
Renommez ça plz. En « Anime non vus » par ex.

**Comment by RaitoBezarius** [comment]
Either we keep it as-is, either we kill wontsee animes from our views. It's taking too much space and people will not see them anyway in 99 % of cases. Rather than adding a tab per work type, we could kill them. Or rethink completely the view.

**Comment by SubaruSumeragi** [comment]
I like the idea of killing th won't see from the views.
