### ISSUE TITLE
Lors de l'affichage d'une carte, il ne faut pas échapper le HTML (|safe)

### ISSUE THREAD

**Issue by jilljenn** [mangaki/mangaki#453]
Cf. [la fiche de Kaiba](https://mangaki.fr/anime/?search=kaiba).

**Comment by SubaruSumeragi** [comment]
Le good first issue est un peu exagéré ici :)

Réussi à faire la modif dans work_rating.hml (cf branche soubi/htmlSafe), ce qui fonctionne dans le cas hors mosaïque de recommandation.

Par contre n'étant que ultra débutant en Python j'ai du mal à voir où rajouter un mark_safe() sur le synopsis dans le cas d'une mosaïque de recommandation où les cartes sont chargées via l'API JS et via card.py, si vous avez des pistes je suis preneur ;)
