### ISSUE TITLE
Incohérence de l'opacité des boutons de vote

### ISSUE THREAD

**Issue by Elarnon** [mangaki/mangaki#47]
Lorsque l'on va sur la page d'une oeuvre pour laquelle on n'a pas voté, les boutons de vote sont opaques, et si l'on clique sur un bouton pour voter, tous les autres boutons deviennent semi-transparents pour indiquer notre vote.

Mais si l'on clique à nouveau sur le bouton pour annuler notre vote (par exemple à cause d'un misclick), il devient semi-transparent - ce qui indique exactement la même chose que si tous les boutons étaient opaques. 

Par cohérence, l'une des deux solutions suivantes devraient être implémentées :
 - Faire commencer tous les boutons en mode semi-transparent
 - Ou, remettre tous les boutons opaques après un vote

Qu'en pensez-vous ?

**Comment by jilljenn** [comment]
J'aime bien actuellement qu'un clic ne change au plus l'état que d'un seul bouton, sauf quand il s'agit de mettre en valeur un vote.

Mais c'est sûr que faire commencer tous les boutons en mode semi-transparent n'est pas pratique du tout. Donc si je dois choisir une option c'est la 2e. Et je pense que c'est une bonne idée.

Pendant qu'on y est, comme il est difficile d'identifier à quoi correspondent les icônes malgré la légende, je pense que ce serait bien de faire comme pour le CSS des [boutons sociaux en bas de cette page](http://jiji.cat/2015/08/31/osaka.html), des `content: attr(title)` qui permettent d'avoir des *infobox* instantanées et non qui apparaissent après 2 secondes d'attente.

**Comment by Elarnon** [comment]
OK; l'option 2 me parait la meilleure aussi - en l'implémentant, j'ai réalisé que cela permettait aussi de distinguer visuellement l'état "un vote a été choisi" de l'état "pas de vote choisi" même avec la souris sur un bouton de choix.

Niveau CSS avec du `content: attr(title)`, ça a probablement sa place dans une issue différente (en particulier il faut résoudre la question de "où met-on l'infobulle, et avec quel style ?").

**Comment by RaitoBezarius** [comment]
@Elarnon: La nouvelle issue a été ouverte dans #53 !
