### ISSUE TITLE
Generate fake data for compare / testing

### ISSUE THREAD

**Issue by RaitoBezarius** [mangaki/mangaki#470]
We should test our algorithms.

An interesting way would be to generate fake data such as the `U, V` for matrix completion algorithms and compute `UV^T` as truth source.

**Comment by jilljenn** [comment]
It is now done in [test_algo.py](https://github.com/mangaki/mangaki/blob/master/mangaki/mangaki/tests/test_algo.py).

Could you please add a `--fake` parameter in compare? It would be great if the test was launching that management command, because it would increase coverage. What do you think?

**Comment by jilljenn** [comment]
(To be honest, I have my own `test_algo` management command because it is faster to launch than tests…)

**Comment by RaitoBezarius** [comment]
You can also run `nosetests` on a subset of tests to avoid running all the tests.
We could add such a flag for `compare`.

**Comment by jilljenn** [comment]
Still, the generation of the test database in PostgreSQL is uselessly long.
(It's safe, of course, but not for prototyping.)

**Comment by jilljenn** [comment]
Fixed in #495.
