### ISSUE TITLE
Prevent beta deployment to be indexed by search engine

### ISSUE THREAD

**Issue by RaitoBezarius** [mangaki/mangaki#492]
Either we add a no index in the headers on the web server, either we add it in the HTML templates.

**Comment by SubaruSumeragi** [comment]
Why not in robots.txt file ? (and add it in .gitignore to have a robots.txt by plateforme)

**Comment by RaitoBezarius** [comment]
I'm not exactly sure this is sufficient, but yeah, ultimately, we'll want to add some `robots` file.

**Comment by jilljenn** [comment]
Please just do it!

**Comment by RaitoBezarius** [comment]
To be tracked in https://github.com/mangaki/machines/issues/1
