### ISSUE TITLE
Tests unitaires pour Django ?

### ISSUE THREAD

**Issue by RaitoBezarius** [mangaki/mangaki#5]
![Meme](https://i.imgflip.com/wbudj.jpg)

Non, sérieusement, ça serait bien qu'on commence à avoir une couverture en tests.

**Comment by jilljenn** [comment]
On y songe. On est d'accord qu'il faudrait une sorte de JSONResponseMixin afin de tester la plupart des réponses en API REST ?

**Comment by RaitoBezarius** [comment]
Oui probablement, mais tester une API REST est encore plus simple, car suffit juste d'inspecter le résultat JSON en dict Python.

**Comment by vendethiel** [comment]
J'ai besoin de docs sur ce coup :). Comment python gère les fixtures, etc, pour ce genre de cas.

**Comment by RaitoBezarius** [comment]
Bon avant de tester le JSON, les views & compagnie.

Il y a un truc encore plus simple à faire et aussi important:

> Tester si les pages publiques retournent 200.

Donc je propose ce plan d'action:

- [ ] Tester si les pages publiques retournent 200.
- [ ] Tester si les pages utilisateurs retournent 200 (si le contexte est ok -- genre connecté, et tout).
- [ ] Tester si les migrations marchent.
- [ ] Tester si les fixtures (les seeds) marchent.
- [ ] Tester si les emails s'envoient correctement ([docs](https://docs.djangoproject.com/es/1.9/topics/testing/tools/#topics-testing-email)).

Une fois qu'on aura fait ça, on aura une belle couverture déjà.

**Comment by RaitoBezarius** [comment]
Fermé, il faudra continuer le travail sur d'autres issues:

- Linter le code qui a changé, par exemple.
