### ISSUE TITLE
Ajout de SSL

### ISSUE THREAD

**Issue by Elarnon** [mangaki/mangaki#52]
Maintenant que https://letsencrypt.org est en beta publique, il n'y a plus de raison pour Mangaki d'être accessible en HTTP seulement.

**Comment by RaitoBezarius** [comment]
@jilljenn On te laisse faire la requête des certificats? Ou je m'en charge?

**Comment by RaitoBezarius** [comment]
@elarnon: Je fais la demande ce weekend normalement.

**Comment by jilljenn** [comment]
Je veux bien que tu t'en charges parce que je ne connais pas du tout même si ça m'intéresse :)

**Comment by Elarnon** [comment]
Reporté en 0.2

**Comment by jilljenn** [comment]
https://mangaki.fr

Si vous voulez automatiser le playbook : https://jeffbradberry.com/posts/2016/01/getting-started-with-lets-encrypt/ mais je mets la carte pour une milestone ultérieure.

**Comment by jilljenn** [comment]
Great!
