### ISSUE TITLE
Internal error when importing from MAL

### ISSUE THREAD

**Issue by emersion** [mangaki/mangaki#523]
```
HTTP/1.1 500 Internal Server Error
Server: nginx/1.10.3 (Ubuntu)
Date: Sun, 19 Nov 2017 23:00:25 GMT
Content-Type: text/html
Content-Length: 27
Connection: keep-alive
X-Frame-Options: SAMEORIGIN
Vary: Accept-Language, Cookie
Content-Language: en

<h1>Server Error (500)</h1>
```

See #475

**Comment by jilljenn** [comment]
Attention tu as testé sur https://beta.mangaki.fr ? Parce que sur la prod on sait que ça peut être cassé.

**Comment by RaitoBezarius** [comment]
@emersion Désolé, j'aurais dû précisé que c'était fermé sur master mais pas encore sur stable. On ferme cette issue lorsque #498 arrive sur stable, ça te va?

**Comment by emersion** [comment]
Ahah, désolé j'ai mal compris moi aussi, j'ai vu que la PR a été fusionnée il y a un mois donc je me suis dit que c'était déjà stable. :3

Si master n'a plus ce bug, ça ne sert a rien de garder cette tache ouverte,  je ferme !
