### ISSUE TITLE
Mise à jour des ratings

### ISSUE THREAD

**Issue by SubaruSumeragi** [mangaki/mangaki#524]
L'import MAL devrait pouvoir mettre à jour les ratings si le work a déjà été noté par l'utilisateur ré-important sa MAL.

**Comment by jilljenn** [comment]
Ce n'est pas déjà le cas ?

**Comment by SubaruSumeragi** [comment]
Pas de ce que j'ai pu tester de la nouvelle implémentation sur beta

**Comment by RaitoBezarius** [comment]
OK, intéressant, je vais debugger ça alors, @SubaruSumeragi
