### ISSUE TITLE
Si on se trompe de nom d'utilisateur ou de mot de passe, il faut un message d'erreur

### ISSUE THREAD

**Issue by jilljenn** [mangaki/mangaki#551]
Thanks Mota :}

**Comment by jilljenn** [comment]
(bizarre, je n'arrive pas à reproduire, en aucune langue)

**Comment by jilljenn** [comment]
OK ça venait d'un `{{ form.non_field_errors }}` manquant.

Source : https://stackoverflow.com/a/16215790/827989

**Comment by Elarnon** [comment]
En fait c'est déjà possible d'énumérer les adresses mail à partir du formulaire de création de compte et interdire de les lister par le formulaire de connection n'apporte rien en termes de sécurité, en plus de rendre la procédure plus désagréable pour les utilisateurs.

**Comment by jilljenn** [comment]
Bizarre que j'aie trouvé le souci mais que j'aie pas corrigé. Du coup là j'ai dû retrouver le souci —__—
