### ISSUE TITLE
Améliorer l'affichage de la mosaïque

### ISSUE THREAD

**Issue by Elarnon** [mangaki/mangaki#57]
Si l'on regarde le screenshot ci-joint, on peut s'apercevoir de deux choses:

1. Les boutons de votes pour Princesse Mononoké sont **plus proches de l'image de Sword Art: Online que de celle de Princess Mononoke**, ce qui est perturbant (surtout pour un nouvel utilisateur qui n'est pas habitué à ce que Mangaki mette toujours les boutons de vote sur la droite de l'oeuvre). Ils sont beaucoup plus proches sur la page de détails de l'oeuvre, en revanche.
2. ll est peu clair, pour quelqu'un qui ne connaît pas déjà les oeuvres, de déterminer si l'affiche de Princesse Mononoké correspond à Princesse Mononoké ou à Naruto Shippuden (idem pour SAO et Fairy Tail), puisque le titre est approximativement à égale distance des deux et qu'aucun indice visuel ne permet de faire la différence. Personnellement, bien que je sache pertinemment que le titre est en haut si je me pose la question consciemment, il m'arrive de nombreuses fois de me tromper.

<img width="592" alt="screen shot 2016-01-13 at 00 56 46" src="https://cloud.githubusercontent.com/assets/146210/12280739/93d12184-b990-11e5-92c5-955a7ef2b361.png">

Afin de pallier à ces problèmes je propose de rapprocher les boutons de vote de l'oeuvre à laquelle ils correspondent, et de rapprocher les titres de l'oeuvre à laquelle ils correspondent.

**Comment by RaitoBezarius** [comment]
J'aurais tendance à dire que c'est même un bug qui doit être fixer car il peut nuire beaucoup à l'utilisation de l'interface de Mangaki.

**Comment by vendethiel** [comment]
Je propose de bouger le nom en **dessous** du poster :). Tous les gens à qui j'ai fait découvrir mangaki se sont faits avoir (.. et moi donc)

**Comment by Elarnon** [comment]
J'approuve la proposition de bouger le nom en dessous du poster, je me fais souvent avoir aussi. Je me demande aussi si cela vaudrait le coup de mettre les informations (poster + boutons de vote + nom) dans une vignette (bordure) qui sépare visuellement les oeuvres (un peu comme le fait par exemple [Hummingbird](https://hummingbird.me/anime/filter/all), mais avec les boutons de vote en plus).
