### ISSUE TITLE
API MyAnimelist

### ISSUE THREAD

**Issue by SubaruSumeragi** [mangaki/mangaki#571]
Ca fait à peu prêt 10 jours que l'API MAL est HS et qu'il n'y a aucune news sur sa remise en place ou sur la mise en place d'une nouvelle API.

Envisage-t-on de passer vers une autre API pour importer les nouveau titre (Anilist, Anidb, Kitsu, ...) ?
Idem pour l'import l'import des MAL : Envisage-t-on de repasser à l'import via fichier XML, dans ce cas quid des oeuvres non-trouvées en base que l'on ne peut importer depuis MAL ?

**Comment by RaitoBezarius** [comment]
I think I will add soon AniList import, a lot of work has been done in #543 and I just have to assure myself that no duplicates will be born from a new importer system.

If we import through an XML file and we don't know the work, we can always use AniDB / AniList to find it.

**Comment by jilljenn** [comment]
At least we removed it from the frontend.
