### ISSUE TITLE
The WorkCluster admin page makes too many queries

### ISSUE THREAD

**Issue by jilljenn** [mangaki/mangaki#581]
CPU: 9.8s
SQL: 553 queries in 659ms

**Comment by jilljenn** [comment]
Partial solution: use [`list_select_related`](https://docs.djangoproject.com/en/dev/ref/contrib/admin/#django.contrib.admin.ModelAdmin.list_select_related).

If I remove the list of titles of works on which the cluster is being made:

CPU: 924ms
SQL: 4 queries in 10ms

But if I don't:

CPU: 5.7s
SQL: 259 queries in 180ms

So I prefer to remove fetching the list of titles of works. It creates too many queries because we have to search in `Work.all_objects` (remember: works being redirected are invisible).

**Comment by RaitoBezarius** [comment]
I suggest we have some kind of purge mechanism to remove some of our oldest invisible works in order to reduce strain on the database / etc.
