### ISSUE TITLE
Notation anonyme des animes / manga

### ISSUE THREAD

**Issue by RaitoBezarius** [mangaki/mangaki#59]
Comme l'a dit @Sedeto dans #50, on a notre super algorithme mais... Pas de notation anonyme!

On devrait pouvoir permettre aux invités de noter, et de transférer leur note à leur nouveau compte si ils désirent s'inscrire.

**Comment by RaitoBezarius** [comment]
Je pense que la notation anonyme est dépendante d'utiliser ALS ou SVD en production plutôt que KNN, voire #139.

**Comment by RaitoBezarius** [comment]
That being said.

There are three big steps for this issue:

- [ ] Make it possible to get recommendations from a session (e.g. a real user or unregistered visitor).
    - look for `views.get_reco_list`
    - look for `views.rate_work`
    - look for `views.remove_reco`
    - look for `views.get_reco`
- [ ] Add support for anonymous recommendations (UI + new routes potentially).
    - "do you want to keep your ratings?"
- [ ] Handle edge cases when
   - the user sign up / in with a session full of different ratings.

@Elarnon Please, feel free to correct me on these points (especially the second), I am really sorry to forget so quickly what you said!

**Comment by jilljenn** [comment]
J'imagine qu'il faudra avoir une interface un peu comme lorsqu'on merge sur GitHub et qu'il faut choisir entre :

- theirs
- ours

Peut-être que la vue work_no_poster est bien pour cela ?

**Comment by RaitoBezarius** [comment]
@jilljenn Right, but the drawback is: if you forgot you were logged out and was rating, then logged in [1].
You may want to "merge" the ratings or select the ones to keep.

[1] : This issue is about anonymous ratings, and not merging ratings, so we may prefer to not support such feature for now.

**Comment by Elarnon** [comment]
Let's recap the technical points as I see them:

 - Step 1 is indeed to decouple the "do stuff with the ratings" (like give a recommendation or display the ratings on a work) from the ratings storage.
 - Step 2 I would say is to *transparently* route the ratings for an anonymous user to a session storage instead of the database. This shouldn't be visible to the user (and should probably be implemented in a `get_user_ratings(user)` function that would dispatch appropriately based on `user.is_anonymous`), except maybe for a heads-up (e.g. in a banner) that there are unsaved ratings.
 - Step 3 is indeed the tricky part of merging. We can start thinking about this, but work on step 1 and step 2 can (and should) probably start right now.

On step 3, here are some thoughts:

 - Ideally, we don't want the merging to interrupt the sign-in or (especially) sign-up workflow for the user. This means that an additional screen asking them to review their ratings may not be the best tool for that: alternatives include keeping track of which ratings were made offline (esp. the date they were made at) and making them available in a special "to review" area of the profile.
 - In any case (whether that screen should be shown on sign-in/sign-up or on a review area), we need a review screen that at least allows the following scenarios:
    - The user rated some previously unrated works while offline, and they (a) want to import all of those ratings to their profile (b) want to discard all of those (e.g. the website was used to show a demo) (c) want to selectively choose which new ratings to keep and which to discard - and potentially even import those ratings but change them.
    - The user rated again some previously rated works while offline, and they gave it the same rating as before. In that case, we shouldn't do anything.
    - The user rated again some previously rated works while offline, and they gave it a different rating. In that case we should allow them to (a) import all the new ratings to their profile (b) ignore all the new ratings and keep the existing ones (c) selectively choose which ratings to import and which to discard. Note that in this case (c) is challenging in terms of UI because we need to find a way to display *both* informations, i.e. which rating was there previously and which rating is the new one.

This is all very raw, but I agree with @jilljenn that adapting the `work_no_poster` view for this would probably be the way to go. I don't get the drawback you are talking about @RaitoBezarius, can you precise what you meant?

**Comment by jilljenn** [comment]
My two additional cents:

- You should cut this issue into several short PR such as:
    - allow anonymous users to rate works and receive recommendations (this may be your step 1);
    - provide a banner in the profile whenever there are “some ratings left in the session”, possibly with two columns: “These ratings will be added/removed” and “These ratings need further attention” (collisions, with maybe two colors?);
    - redirect user login towards profile in this case, not anime list.
- Please start to work on Step 1 asap :D 頑張って！

**Comment by vendethiel** [comment]
I'm not sure I follow. Seems to me like **logging in** after rating anonymously is a non-issue / non-feature – at least I don't know of any website that provides it.

The one thing I see often, however, and the one that makes sense to me is **registering** after submitting anonymous ratings.
No need for merge/... then

**Comment by jilljenn** [comment]
It depends. What if you were just showing the website to some friend, then use the service while forgetting to log in again?

**Comment by Elarnon** [comment]
Some progress was made towards this in #277 and #278. Remaining work:
- Figure out the right UI for importing the ratings on login/signup
- Display the current anonymous ratings, similar to the profile view, but for the current anonymous user.
- Add a heads-up banner that there are unsaved, anonymous ratings. This should probably also provide an easy way to show these ratings (cf previous item) & to clear them.

**Comment by RaitoBezarius** [comment]
@Elarnon Do you agree that for this item:
> Display the current anonymous ratings, similar to the profile view, but for the current anonymous user.
that we can reuse `get_profile` view and just add logic to handle anonymous ratings in it.

Of course, there'll be some changes to the template.
Here is what I have:
![Screenshot of anonymous profile](https://sc-cdn.scaleengine.net/i/1f6d97c11a59c9b819043fd87176fad2.png)

What do we want to have on this view more exactly?

### Clearing ratings

To clear ratings, I'm not exactly sure what would be the simpler way: do we want to have another view where we can clear a rating from a list similar to the profile one, or rather do we want a "Clean all" button.

### Removing a rating

Removing a rating should be on the rate UI (i.e. where you rate works).

### Heads-up banner 

I guess an inclusion tag is enough, we can put near to the cookielaw tag.

**Comment by Elarnon** [comment]
I think this is good; I would remove the "Amateur de culture japonaise anonyme" part and replace it with something like "Mes notes" + a subtitle "Connectez-vous pour sauvegardez vos notes" or something.

Clearing ratings / removing a rating -> we want the same UI there is in your own profile or the list that is displayed on the signup view on #279.

Heads-up banner -> I would put it under the menu personally.

**Comment by Elarnon** [comment]
<img width="939" alt="screen shot 2017-04-07 at 01 45 25" src="https://cloud.githubusercontent.com/assets/146210/24779941/e529db42-1b33-11e7-98c0-06d4d597fefd.png">
Talking about this view, (works_no_poster in "edit mode").

**Comment by RaitoBezarius** [comment]
Right, I'll try to submit something tomorrow. Thanks :).

**Comment by RaitoBezarius** [comment]
- We should inform a user when he's logging in using social auth.
- We should move the "merge anonymous ratings with user's ratings when conflicts arise" to 0.4 / 0.5

Let's track it in #310.
