### ISSUE TITLE
Pages statiques

### ISSUE THREAD

**Issue by Elarnon** [mangaki/mangaki#6]
Certaines pages de Mangaki (par exemple http://mangaki.fr/top/directors/ accessible depuis la barre principale) sont statiques et donnent l'impression d'avoir été déconnecté alors que ce n'est pas le cas.

**Comment by jilljenn** [comment]
En fait il serait plus intelligent de générer une page Markdown avec le classement :
https://github.com/mangaki/mangaki/blob/master/mangaki/mangaki/models.py#L104

Actuellement, le top est généré via `./manage.py top director > director.json`. On pourrait même en faire une action admin.
