### ISSUE TITLE
Le serveur est en Python 3.5 (désolé les gens)

### ISSUE THREAD

**Issue by jilljenn** [mangaki/mangaki#648]
Il faut modifier le service systemd.

**Comment by jilljenn** [comment]
En fait, le serveur est encore sous 16.04. Je passe à 18.04 @RaitoBezarius ?

Source: https://askubuntu.com/a/865569/587263

**Comment by RaitoBezarius** [comment]
@jilljenn Ça dépend à quel point tu as des services « legacy » sur ton serveur, mais pourquoi pas ? :)

**Comment by RaitoBezarius** [comment]
La PR #666 (nice number!) va forcer Python 3.6 et plus, donc cette issue sera forcément fermée bientôt

**Comment by jilljenn** [comment]
Bientôt qu'il disait
