### ISSUE TITLE
CDN MAL

### ISSUE THREAD

**Issue by SubaruSumeragi** [mangaki/mangaki#653]
L'URL du CDN MAL a été modifié de myanimelist.cdn-dena.com en cdn.myanimelist.net, il faudrait donc inverser la valeur des constantes FORMER_CDN  et NEW_CDN introduite avec la PR #347

**Comment by jilljenn** [comment]
Mince :/ Je veux en profiter pour utiliser le poster local s'il existe.

**Comment by jilljenn** [comment]
I almost want the BASE_URL to be defined somewhere in the admin to avoid adding these kinds of migrations in the future.
