### ISSUE TITLE
Canonicalisation des URLs

### ISSUE THREAD

**Issue by Elarnon** [mangaki/mangaki#66]
Il faudrait gérer /{work,anime,manga}/{id}/{slug} d'une façon cohérente.

Possiblités :
 - /{work,anime,manga}/{id}/{slug} ignore le {slug} et fait un 303 vers la catégorie canonique (e.g. /manga/1 et /work/1 redirigent vers /anime/1 car le work numero 1 est l'anime Death Note) et le slug canonique
 - /{work,anime,manga}/{slug} fait un 303 vers la catégorie canonique
 - /{work,anime,manga}/{slug} fait un 303 vers la catégorie canonique et l'ID
 - /{work,anime,manga}/{id} fait un 303 vers la catégorie canonique
 - /{work,anime,manga}/{id} fait un 303 vers la catégorie canonique et le slug canonique
etc.

**Comment by Elarnon** [comment]
Depend de l'unififcation des oeuvres.

**Comment by Elarnon** [comment]
(Il faut en discuter en revanche)

**Comment by Elarnon** [comment]
Après #132, ceci est maintenant trivial à implémenter, il faut juste déterminer quel schema d'URLs adopter.

**Comment by RaitoBezarius** [comment]
OK, on va laisser ça en fin de 0.1 je pense
