### ISSUE TITLE
map is broken

### ISSUE THREAD

**Issue by louisabraham** [mangaki/mangaki#663]
<https://mangaki.fr/map/>

probably caused by the 404 on

- https://openlayers.org/en/v4.5.0/css/ol.css
- https://openlayers.org/en/v4.5.0/build/ol.js

Possible fix: replace with 

- https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v5.3.0/css/ol.css
- https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v5.3.0/build/ol.js

(from <https://openlayers.org/en/latest/doc/quickstart.html>)

**Comment by jilljenn** [comment]
It's back thx!
