### ISSUE TITLE
Use Poetry

### ISSUE THREAD

**Issue by RaitoBezarius** [mangaki/mangaki#664]
[Poetry is the package manager Python deserves.](https://poetry.eustace.io/)

More seriously. 

Pros are that we will able to lock our dependencies and make them deterministic because [pip has no real dependency resolver](https://github.com/pypa/pip/issues/988).

Cons is we are adding yet another tool to the belt, but one I believe will be a fairly standard one.

**Comment by NeolithEra** [comment]
Hi, maybe you can try a dependency diagnosis website http://www.watchman-pypi.com/dependency_analysis, which can help diagnoze dependency conflict problems and automatically visualize your dependency tree and those of your downstream projects.

Best,
Neolith

**Comment by RaitoBezarius** [comment]
@NeolithEra Why do you think this is a problem we have?

**Comment by pradyunsg** [comment]
@RaitoBezarius That user has been spamming all kinds of issues and PR with exactly that message.
