### ISSUE TITLE
Translate shortcuts

### ISSUE THREAD

**Issue by jilljenn** [mangaki/mangaki#709]
Shortcut messages are not translated yet:
https://github.com/mangaki/mangaki/blob/17ec0f2ed72da5b81323bbb62b42991cf816a6f0/mangaki/mangaki/templates/mangaki/work_list.html#L49

**Comment by mirukyu** [comment]
translations need to be added for :
Voter
Aller à gauche
Aller à droite

**Comment by jilljenn** [comment]
Thanks @mirukyu!
