### ISSUE TITLE
Fix CSS of shortcut messages

### ISSUE THREAD

**Issue by jilljenn** [mangaki/mangaki#710]
For some reason, h3 and h4 are visually stuck to each other here:
https://github.com/mangaki/mangaki/blob/17ec0f2ed72da5b81323bbb62b42991cf816a6f0/mangaki/mangaki/templates/mangaki/work_list.html#L56

**Comment by mirukyu** [comment]
From what I found it is because the box is using a format in CSS we could just add ```justify-content: space-between;``` in the CSS and that would solve the problem but I don't know if that is very appealing.
![image](https://user-images.githubusercontent.com/28414051/126142901-f6deca93-38f5-4c6e-9539-3e50392f4e7d.png)
