### ISSUE TITLE
Group recommendations: simple version

### ISSUE THREAD

**Issue by jilljenn** [mangaki/mangaki#737]
We want to provide group recommendations on Mangaki.fr as soon as possible, as there are many
groups of people who want to watch content together (especially during the pandemic) but do not 
know where to start.

Milestone(s)
- [x] Several methods for computing the group recommendations (average, min)
- [x] People should be able to add friends on Mangaki.fr and compute recommendations

For this second part:
- Add a favorite attribute in Profile which is a many-to-many relation to User
- Add a button to add users to its favorites
- Add a select (multiple) with favorite users in the page of recommendations
- Connect the corresponding code from mangaki-zero (notably dealing with recommendations for a group of people)

**Comment by Akulen** [comment]
Current progress:

- [x] 0355978d4b4567c320283cb8322ccecbc7453527 Added friend relation to Profile and a button to create them on the profile page
- [ ] Add a select (multiple) with favorite users in the page of recommendations
- [ ] Connect the corresponding code from mangaki-zero (notably dealing with recommendations for a group of people)
