### ISSUE TITLE
Lien "Nom utilisateur" du header

### ISSUE THREAD

**Issue by SubaruSumeragi** [mangaki/mangaki#74]
Il y a un lien sur le nom de l'utilisateur dans la barre de header ne renvoyant vers rien.

Deux solutions : 
1- On le supprime
2- On met un lien vers la page profil de l'utilisateur

![capture d ecran - 23012016 - 21 42 51](https://cloud.githubusercontent.com/assets/4798290/12532699/67018198-c21a-11e5-8180-08d110000794.png)

**Comment by Elarnon** [comment]
Il me semble que bootstrap a besoin de la présence de ce lien pour afficher correctement le menu, donc je penche pour la solution 2.

**Comment by Elarnon** [comment]
C'est dans [mangaki/mangaki/templates/base.html, ligne 101](https://github.com/mangaki/mangaki/blob/master/mangaki/mangaki/templates/base.html#L101).
