### ISSUE TITLE
Automatiser la création d'événements

### ISSUE THREAD

**Issue by jilljenn** [mangaki/mangaki#85]
Notamment pour Studio Ghibli Party, on pourrait scraper les horaires :
http://www.cinemalesfauvettes.com/cycle/studio-ghibli-party.html

Ce qu'on pourrait faire, c'est une sorte de format standard avec une option d'importation dans le panneau admin, par exemple :

    DD/MM/YYYY HH:MM titre ; lieu ; VF/VOSTFR/VOSTA

Je vais commencer un notebook. Ce serait bien que quelqu'un d'autre le complète.

**Comment by vendethiel** [comment]
oulah, pourquoi essayer d'inventer un format? pourquoi pas juste stocker ça en json ou un truc du genre?

**Comment by jilljenn** [comment]
En fait ma première pensée était que c'était plus facile pour ajouter des événements en bulk. Mais un compromis est YAML.

En tout cas, ça a été résolu dans https://github.com/mangaki/mangaki/pull/90.

Ce qui est pénible, c'est de faire le pairing titre et Anime. C'est l'éternel problème.
