### ISSUE TITLE
Donner des noms aux vues

### ISSUE THREAD

**Issue by Elarnon** [mangaki/mangaki#88]
Il serait bon de donner des noms aux vues et de créer les url à l'aide de `{% url %}` au lieu de les hardcoder.

**Comment by jilljenn** [comment]
Ainsi au lieu d'avoir dans les templates des liens de type `href="/"`, on aura `href="{% url "home" %}"` ce qui est plus pratique le jour où on voudra renommer les URL sans créer des liens morts par inadvertance... Tout l'intérêt du DRY en Python (don't repeat yourself) :)

**Comment by RaitoBezarius** [comment]
Closed via #196, thank you @Sapaing !
