### ISSUE TITLE
Responsivité de la page recommandation à revoir

### ISSUE THREAD

**Issue by SubaruSumeragi** [mangaki/mangaki#92]
La page des recommandation est cassé pour les écrans de largeur <= 767px

1°) Le bouton permettant de recharger les recommandations remonte en haut de la liste
2°) Un élément déforme la page lui donnant une largeur supérieure à celle de l'écran

![2016-01-26_100752](https://cloud.githubusercontent.com/assets/4798290/12576573/f3b339a0-c414-11e5-8452-029e3d3ef756.png)

**Comment by Elarnon** [comment]
`class="col-md-12 col-sm-12"` ahem ahem.

**Comment by RaitoBezarius** [comment]
Fermé dans #100
