### ISSUE TITLE
Ajout de l'apple touch icon

### ISSUE THREAD

**Issue by SubaruSumeragi** [mangaki/mangaki#96]
Ajout d'un <link /> dans les métatags pour un "Apple Touch Icon",  en gros c'est l'icone qui est utilisée quand un utilisateur veut mettre une page web sur la Home de leur téléphone/tablette (oui c'est purement accessoire, mais ça nous évitera de prendre des 404 pour "rien" venant d'utilisateur Apple)

Au minimum on doit avoir une image de 152x152 dédiée à cela. On a déjà sur le serveur /static/img/unknow.png qui rempli ces critères (cf ci-dessous)
![unknown](https://cloud.githubusercontent.com/assets/4798290/12587412/840ee8e8-c454-11e5-86be-ba96c2980306.png)

On garde celle-ci (qui sera copié et renommé pour que cela soit plus sexy qu'unknow) ou une autre (car proche de Tinder donc possiblement confusant pour des utilisateurs) ?

**Comment by SubaruSumeragi** [comment]
Perso j'aime bien celle-ci :)

**Comment by jilljenn** [comment]
Celle-ci :) Merci !
