### ISSUE TITLE
Gérer les doublons

### ISSUE THREAD

**Issue by jilljenn** [mangaki/mangaki#98]
Actuellement, lorsqu'on observe des doublons, il y a beaucoup de choses à considérer. Par exemple :
- Quel objet Work conserver ? La plupart du temps, celui qui a un poster qui fonctionne.
- Quel titre conserver ? Comment faire pour conserver le poster du premier objet mais le titre du second objet ? Peut-être que des select seraient les bienvenus.
- Il ne faut pas oublier de faire pointer les ratings de l'objet Work supprimé vers l'autre.
- Comment détecter que deux auteurs ne font qu'un ?
- Faut-il conserver une grille de passage du nom d'un auteur sur AniDB vers l'objet Artiste que nous avons choisi ? Je pense que oui, sinon les doublons réapparaîtront sans cesse.

C'est pourquoi `doctor.py` tente de poser des questions pour faire ça au mieux. Pour l'essayer :

```
./mangaki/manage.py loaddata fixtures/duplicates.json
./mangaki/manage.py doctor
```

**Comment by SubaruSumeragi** [comment]
Tel que je le vois

1°) Le poster le plus récent
2°) De préférence le français, sinon le transcrit du japonais, peut-être laissé le choix lors de la fusion s'ils sont différents.
Peut-être ajouté la possibilité d'avoir des titres alternatifs ? (comme par exemple Danmachi pour Dungeon ni deai o motomeru no wa machigatteiru darō ka)
3°) La quetion qui va se poser : si l'utilisateur a noté les deux work différemment, quelle notation garde-t-on ?
4°) Si sur la fusion de deux oeuvres, peut-être proposer la possibilité d'un ManyToMany sur les artistes et faire une liste des oeuvres à vérifier après fusion si ce sont vraiment deux artistes vraiment différents associé à l'oeuvre.
Peut-être poser la question à partir d'un certain taux de concordance des chaines de nom.
5°) Oui

**Comment by SubaruSumeragi** [comment]
De ce que j'en ai lu doctor ne peux gérer que les anilmés, je vais chercher comment récupérer une option d'appel (le classe des données par exemple) pour tester celle-ci et que doctor puisse aussi gérer les manga ;)
Pour les mangas le critère discriminant principal d'une fusion sera, à priori, le titre VO

**Comment by jilljenn** [comment]
Ça existe pour les mangas, ça n'existe pas pour les anime.

**Comment by RaitoBezarius** [comment]
@Elarnon `doctor` ne fonctionne que pour les mangas? Pas pour les animes?

**Comment by Elarnon** [comment]
En fait, `manage.py doctor` ne fonctionne que pour les animes, mais il existe une interface dans l'admin pour les mangas (non, ce n'est pas très cohérent...).

**Comment by RaitoBezarius** [comment]
OK, c'est confus ça, j'ai ouvert #151 à ce sujet.

**Comment by jilljenn** [comment]
In [8]: Rating.objects.filter(user_id=84, work_id__in=[46, 14329])
    Out[8]: [<Rating: Maxime willsee Psycho-Pass>, <Rating: Maxime like Psycho-Pass>]

:'(

**Comment by jilljenn** [comment]
Bon les dernières discussions qu'on a eues me permettent de dresser des spec plus précises.

## Gestion des alias

Il existe déjà une classe `ArtistSpelling` avec deux attributs `was` (une chaîne) et `artist`. Il faut faire la même chose pour les objets `Work` : une classe `WorkSpelling` (le champ `was` doit être unique).

## Artist

- Lorsqu'on fusionne deux artistes, il faut mettre à jour les entrées `ArtistSpelling` correspondantes
- On peut également renommer un artiste mais demander à si on conserve l'orthographe ou pas. Idéalement, sur une page d'artiste, les objets `ArtistSpelling` correspondants seraient en inline.

## Work

- Lorsqu'on fusionne deux œuvres depuis l'admin, cela déclenche une page avec des boutons radio pour sélectionner le texte conservé, le poster conservé (options par défaut : celles d'ID maximal) et *panique* le staff conservé¹.
- Lorsque un user a voté pour les deux objets de la fusion (merci @SubaruSumeragi), il faut considérer une priorité pour le rating conservé, je suggère : `wontsee < willsee < neutral < dislike < like < favorite`.

¹ Je me demande si le plus simple ne serait pas de fusionner sauf les doublons triviaux, et ensuite de rediriger vers la page de l'œuvre fusionnée, où on pourrait justement éliminer le staff facilement via les inline.

**Comment by Elarnon** [comment]
Pourquoi ne pas garder le vote le plus récent lorsqu'un utilisateur à voté pour les deux objets de la fusion plutôt ?

**Comment by Elarnon** [comment]
Aussi, je l'ai évoqué sur Slack, mais je suis favorable à une dénomination `WorkTitle` (`work` foreign key sur `Work` et `title` chaîne).

**Comment by Elarnon** [comment]
Est-ce que ceci ne devrait pas être interverti avec #131 qui semble en être une dépendance mais est dans une milestone postérieure ?

**Comment by jilljenn** [comment]
La recherche de « kill » me donne envie de pouvoir signaler un doublon en cliquant sur plusieurs œuvres de la recherche. Si je fais un hack qui ajoute des cases à cocher à côté des titres, est-ce qu'@elarnon va râler ?

**Comment by RaitoBezarius** [comment]
On peut rajouter les cases seulement si on est admin? Genre en dessous des
boutons de like, dislike, ...
Ou alors on peut faire en sorte que les comptes admins ne puissent pas
voter? Et on leur met que des boutons d'administration ?

On Wed, Jun 29, 2016, 02:56 Jill-Jênn Vie <notifications@github.com> wrote:

> La recherche de « kill » me donne envie de pouvoir signaler un doublon en
> cliquant sur plusieurs œuvres de la recherche. Si je fais un hack qui
> ajoute des cases à cocher à côté des titres, est-ce qu'@elarnon
> <https://github.com/elarnon> va râler ?
>
> —
> You are receiving this because you commented.
>
> Reply to this email directly, view it on GitHub
> <https://github.com/mangaki/mangaki/issues/98#issuecomment-229227644>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AATMxGKmm3xYr0XOKz5YpwIZTA-MVBPFks5qQcLYgaJpZM4HMx8q>
> .
>
-- 

-- 

Ryan Lahfa, from my phone.

**Comment by jilljenn** [comment]
On pensait déjà qu'ajouter des boutons selon si on est admin ou pas n'était pas une bonne idée (confusion++).
Je suggérais des cases à cocher, @Elarnon suggère un drag-and-drop. C'est vrai que c'est plus cool, après c'est un peu plus difficile à coder :)

**Comment by RaitoBezarius** [comment]
→ Drag-and-drop c'est pas mauvais comme idée.

**Comment by jilljenn** [comment]
C'est moins responsive en fait. Donc on opte pour les cases ?

**Comment by RaitoBezarius** [comment]
@jilljenn Could you do an update on this issue?

- Is [dedupe](https://github.com/datamade/dedupe) sufficient to handle most of the cases?
- Can we help you?

**Comment by jilljenn** [comment]
FIXED.
